ARG version
FROM almalinux:${version}
ARG author="venkata koti" \
    tool="docker" \
    description="this is docker practice"
RUN echo "Name:$author,Tool:$tool,Description:$description"
CMD ["sleep","120"]